server:
  port: 8899

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bgur?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false
    username: bgur
    password: tzXr9ejizlvxlDR
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20         # 最大连接数（根据业务并发量调整）
      minimum-idle: 5               # 最小空闲连接数
      idle-timeout: 30000           # 空闲连接超时时间（毫秒）
      max-lifetime: 1800000         # 连接最大存活时间（毫秒）
      connection-timeout: 30000     # 获取连接的最大等待时间（毫秒）
      auto-commit: true            # 关闭自动提交（交由事务管理控制）

  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: C2k9hxZw1yeFC2w

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
